In [21]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('output/test.csv', header=None, names=['year','gender','name','count'])
df

        year  gender       name  count
0       1944  female   MARGARET    341
1       1944  female      HELEN    209
2       1944  female     JUDITH    189
3       1944  female   PATRICIA    186
4       1944  female     PAMELA    160
5       1944  female  ELIZABETH    153
6       1944  female   JENNIFER    149
7       1944  female    BARBARA    147
8       1944  female   LORRAINE    143
9       1944  female  CHRISTINE    135
10      1944  female   BEVERLEY    114
11      1944  female     JANICE    107
12      1944  female     SANDRA    107
13      1944  female    LYNETTE    106
14      1944  female    JILLIAN     98
15      1944  female      JANET     97
16      1944  female       MARY     96
17      1944  female    HEATHER     94
18      1944  female    SHIRLEY     93
19      1944  female    RAELENE     81
20      1944  female   ROSEMARY     78
21      1944  female    PAULINE     77
22      1944  female      WENDY     73
23      1944  female    MARLENE     69
24      1944  female     DIANNE     68
25      1944  female        KAY     68
26      1944  female     MAXINE     65
27      1944  female       JOAN     62
28      1944  female   KATHLEEN     60
29      1944  female       KAYE     60
...      ...     ...        ...    ...
210909  2013    male     ZAVIEN      1
210910  2013    male     ZAYAAN      1
210911  2013    male     ZAYDAN      1
210912  2013    male     ZAYDON      1
210913  2013    male     ZAYVIN      1
210914  2013    male      ZEAKE      1
210915  2013    male   ZEBADIAH      1
210916  2013    male    ZEBEDEE      1
210917  2013    male        ZED      1
210918  2013    male      ZEIKE      1
210919  2013    male        ZEN      1
210920  2013    male     ZENITH      1
210921  2013    male  ZEPHANIAH      1
210922  2013    male     ZEPHER      1
210923  2013    male     ZEPHYR      1
210924  2013    male       ZETH      1
210925  2013    male        ZEV      1
210926  2013    male       ZEXI      1
210927  2013    male       ZEYU      1
210928  2013    male        ZHE      1
210929  2013    male    ZHICHEN      1
210930  2013    male    ZHINLAB      1
210931  2013    male    ZHIZHEN      1
210932  2013    male         ZI      1
210933  2013    male     ZIBRAN      1
210934  2013    male       ZIGI      1
210935  2013    male       ZONG      1
210936  2013    male   ZULFIQAR      1
210937  2013    male      ZYLEN      1
210938  2013    male      ZYRON      1

[210939 rows x 4 columns]

In [30]:
df.dtypes

year       int64
gender    object
name      object
count      int64
dtype: object

In [37]:
df['gender'] = df['gender'].astype('category')
# df['name'] = df['name'].astype('string')
df.dtypes

year         int64
gender    category
name        object
count        int64
dtype: object

In [40]:
pd.pivot_table(df, values='count', columns=['year'], index=['gender','name'])

year                         1944  1945  1946  1947  1948  1949  1950  1951  \
gender name
female 'AISYAH                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       'PIAF'                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       'UHEINA-'I-LANGIMA'A   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       (NOT                   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ?LIAM                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A                      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'AFF                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'ARON                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'DELE                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'ISHA                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'ISHAH                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'JANA                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'JANAE                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'LMOS                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A'NETTE                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A-JAY                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       A.J.                   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AABAN                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AABIGAIL               NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AADEN                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AADHARA                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AADHARSH               NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AADHYA                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AADI                   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AADIL                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AADITYA                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AADONEY                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AAESHA                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AAFKE                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       AAFREEN                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
...                           ...   ...   ...   ...   ...   ...   ...   ...
male   ZYDAN                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYE                    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYETH                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYETTA                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYGGY                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYGH                   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYGMUND                NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
       ZYGMUNT                NaN   NaN   NaN   NaN   NaN   NaN   1.0   NaN
       ZYIA                   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYIANE                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYIKA                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYIN                   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYLA                   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYLAH                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYLEN                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYLER                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYLIAH                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYLON                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYMEON                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYNAB                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYNDEL                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYRAH                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYRELL                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYREN                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYRIJE                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYRON                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYRUS                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYSHAN                 NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYTA                   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
       ZYTON                  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

year                         1952  1953  ...   2004  2005  2006  2007  2008  \
gender name                              ...
female 'AISYAH                NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       'PIAF'                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       'UHEINA-'I-LANGIMA'A   NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       (NOT                   NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ?LIAM                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A                      NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A'AFF                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A'ARON                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A'DELE                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A'ISHA                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A'ISHAH                NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A'JANA                 NaN   NaN  ...    NaN   NaN   NaN   1.0   NaN
       A'JANAE                NaN   NaN  ...    NaN   1.0   NaN   NaN   NaN
       A'LMOS                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A'NETTE                NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A-JAY                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       A.J.                   NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AABAN                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AABIGAIL               NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AADEN                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AADHARA                NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AADHARSH               NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AADHYA                 NaN   NaN  ...    NaN   NaN   NaN   NaN   1.0
       AADI                   NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AADIL                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AADITYA                NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AADONEY                NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AAESHA                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AAFKE                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       AAFREEN                NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
...                           ...   ...  ...    ...   ...   ...   ...   ...
male   ZYDAN                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYE                    NaN   NaN  ...    NaN   NaN   1.0   NaN   NaN
       ZYETH                  NaN   NaN  ...    NaN   1.0   NaN   NaN   NaN
       ZYETTA                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYGGY                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYGH                   NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYGMUND                1.0   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYGMUNT                2.0   1.0  ...    NaN   NaN   NaN   NaN   NaN
       ZYIA                   NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYIANE                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYIKA                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYIN                   NaN   NaN  ...    NaN   NaN   NaN   1.0   NaN
       ZYLA                   NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYLAH                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYLEN                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYLER                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYLIAH                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYLON                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYMEON                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYNAB                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYNDEL                 NaN   NaN  ...    NaN   1.0   NaN   NaN   NaN
       ZYRAH                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYRELL                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYREN                  NaN   NaN  ...    NaN   NaN   NaN   NaN   1.0
       ZYRIJE                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYRON                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYRUS                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYSHAN                 NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYTA                   NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN
       ZYTON                  NaN   NaN  ...    NaN   NaN   NaN   NaN   NaN

year                         2009  2010  2011  2012  2013
gender name
female 'AISYAH                NaN   NaN   NaN   NaN   NaN
       'PIAF'                 NaN   NaN   NaN   NaN   NaN
       'UHEINA-'I-LANGIMA'A   NaN   NaN   NaN   NaN   NaN
       (NOT                   NaN   NaN   NaN   NaN   NaN
       ?LIAM                  NaN   NaN   NaN   NaN   NaN
       A                      NaN   NaN   NaN   NaN   NaN
       A'AFF                  NaN   NaN   NaN   NaN   1.0
       A'ARON                 NaN   NaN   NaN   NaN   NaN
       A'DELE                 NaN   NaN   NaN   NaN   NaN
       A'ISHA                 NaN   NaN   NaN   NaN   1.0
       A'ISHAH                NaN   NaN   NaN   NaN   NaN
       A'JANA                 NaN   NaN   NaN   NaN   NaN
       A'JANAE                NaN   NaN   NaN   NaN   NaN
       A'LMOS                 NaN   NaN   NaN   NaN   NaN
       A'NETTE                NaN   NaN   NaN   NaN   NaN
       A-JAY                  NaN   NaN   NaN   NaN   NaN
       A.J.                   NaN   NaN   NaN   NaN   NaN
       AABAN                  NaN   NaN   NaN   NaN   NaN
       AABIGAIL               NaN   NaN   NaN   1.0   NaN
       AADEN                  NaN   NaN   NaN   NaN   NaN
       AADHARA                NaN   NaN   NaN   NaN   1.0
       AADHARSH               NaN   NaN   NaN   NaN   NaN
       AADHYA                 NaN   NaN   NaN   1.0   1.0
       AADI                   NaN   NaN   NaN   NaN   NaN
       AADIL                  NaN   NaN   NaN   NaN   NaN
       AADITYA                NaN   NaN   NaN   NaN   NaN
       AADONEY                NaN   NaN   NaN   NaN   NaN
       AAESHA                 NaN   NaN   1.0   NaN   NaN
       AAFKE                  NaN   NaN   NaN   NaN   NaN
       AAFREEN                NaN   NaN   NaN   NaN   1.0
...                           ...   ...   ...   ...   ...
male   ZYDAN                  NaN   NaN   NaN   NaN   NaN
       ZYE                    1.0   NaN   NaN   NaN   NaN
       ZYETH                  NaN   NaN   NaN   NaN   NaN
       ZYETTA                 NaN   NaN   NaN   NaN   NaN
       ZYGGY                  NaN   NaN   NaN   1.0   NaN
       ZYGH                   NaN   NaN   NaN   NaN   NaN
       ZYGMUND                NaN   NaN   NaN   NaN   NaN
       ZYGMUNT                NaN   NaN   NaN   NaN   NaN
       ZYIA                   NaN   NaN   NaN   NaN   NaN
       ZYIANE                 NaN   NaN   NaN   NaN   NaN
       ZYIKA                  NaN   NaN   NaN   NaN   NaN
       ZYIN                   NaN   NaN   NaN   NaN   NaN
       ZYLA                   NaN   NaN   NaN   NaN   NaN
       ZYLAH                  NaN   NaN   NaN   NaN   NaN
       ZYLEN                  NaN   NaN   NaN   NaN   1.0
       ZYLER                  NaN   NaN   1.0   NaN   NaN
       ZYLIAH                 NaN   NaN   NaN   NaN   NaN
       ZYLON                  NaN   NaN   1.0   NaN   NaN
       ZYMEON                 NaN   NaN   NaN   NaN   NaN
       ZYNAB                  NaN   NaN   NaN   NaN   NaN
       ZYNDEL                 NaN   NaN   NaN   NaN   NaN
       ZYRAH                  NaN   NaN   NaN   NaN   NaN
       ZYRELL                 NaN   NaN   NaN   1.0   NaN
       ZYREN                  NaN   NaN   NaN   NaN   NaN
       ZYRIJE                 NaN   NaN   NaN   NaN   NaN
       ZYRON                  NaN   NaN   NaN   1.0   1.0
       ZYRUS                  NaN   NaN   NaN   NaN   NaN
       ZYSHAN                 1.0   NaN   NaN   NaN   NaN
       ZYTA                   NaN   NaN   NaN   NaN   NaN
       ZYTON                  NaN   NaN   NaN   NaN   NaN

[103034 rows x 70 columns]